var appConstants = {
	FIREBASE_HOST: 'https://pokeapp.firebaseio.com/',
	POKE_BASE: 'http://pokeapi.co/',
	POKE_BASE_FULL: 'http://pokeapi.co/api/v1/',
	GET_POKEDEX: 'GET_POKEDEX',
	GET_CURRENT_POKEMON: 'GET_CURRENT_POKEMON',
	GET_POKE_IMAGE: 'GET_POKE_IMAGE',
	GET_ALTERNATE_IMAGES: 'GET_ALTERNATE_IMAGES',
	CLEAR_ALTERNATE_IMAGES: 'CLEAR_ALTERNATE_IMAGES',
	GET_POKE_DESC: 'GET_POKE_DESC',
	GET_ALTERNATE_DESC: 'GET_ALTERNATE_DESC',
	CLEAR_ALTERNATE_DESC: 'CLEAR_ALTERNATE_DESC',
	NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
	LOADING: 'LOADING'
}

module.exports = appConstants;